In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:/Users/dell/Downloads/Churn_Modelling - Churn_Modelling.csv")

In [4]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
#step 2
X = df.drop(['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)  # Remove unnecessary columns
y = df['Exited']

In [6]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [7]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
le_gender = LabelEncoder()
X['Gender'] = le_gender.fit_transform(X['Gender'])

le_geo = LabelEncoder()
X['Geography'] = le_geo.fit_transform(X['Geography'])

In [9]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64
9996,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,0,0,36,7,0.00,1,0,1,42085.58
9998,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,0,0,28,4,130142.79,1,1,0,38190.78

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
model = Sequential()

In [13]:
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))  # Using ReLU activation
# Hidden Layer
model.add(Dense(32, activation='relu'))  # You can experiment with other activations here (sigmoid, tanh, etc.)
# Output Layer
model.add(Dense(1, activation='sigmoid'))  # Sigmoid for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=30, batch_size=32, validation_data=(X_test_scaled, y_test))

# Step 5: Evaluate the model and print accuracy score and confusion matrix
y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)

C:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.7542 - loss: 0.5210 - val_accuracy: 0.8345 - val_loss: 0.3977
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8346 - loss: 0.3985 - val_accuracy: 0.8535 - val_loss: 0.3601
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8496 - loss: 0.3670 - val_accuracy: 0.8575 - val_loss: 0.3483
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8566 - loss: 0.3537 - val_accuracy: 0.8625 - val_loss: 0.3450
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8562 - loss: 0.3439 - val_accuracy: 0.8610 - val_loss: 0.3469
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8552 - loss: 0.3417 - val_accuracy: 0.8645 - val_loss: 0.3429
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8616 - loss: 0.3309 - val_accuracy: 0.8545 - val_loss: 0.3423
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8627 - loss: 0.3356 - val_accuracy: 0.8575 - val_loss: 0.3423
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8636 - loss: 0.3267 - val_accuracy: 0.8575 - val_loss: 0.3411
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8692 - loss: 0.3192 - val_accuracy: 0.8595 - val_loss: 0.3385
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8636 - loss: 0.3262 - val_accuracy: 0.8605 - val_loss: 0.3403
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8734 - loss: 0.3113 - val_accuracy: 0.8620 - val_loss: 0.3398
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8704 - loss: 0.3143 - val_accuracy: 0.8605 - val_loss: 0.3405
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8642 - loss: 0.3244 - val_accuracy: 0.8625 - val_loss: 0.3371
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8663 - loss: 0.3181 - val_accuracy: 0.8590 - val_loss: 0.3389
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8678 - loss: 0.3195 - val_accuracy: 0.8605 - val_loss: 0.3398
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8663 - loss: 0.3218 - val_accuracy: 0.8575 - val_loss: 0.3393
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8744 - loss: 0.3001 - val_accuracy: 0.8565 - val_loss: 0.3435
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8643 - loss: 0.3199 - val_accuracy: 0.8620 - val_loss: 0.3391
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8700 - loss: 0.3124 - val_accuracy: 0.8615 - val_loss: 0.3396
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3108 - val_accuracy: 0.8645 - val_loss: 0.3379
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8675 - loss: 0.3159 - val_accuracy: 0.8590 - val_loss: 0.3431
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8701 - loss: 0.3079 - val_accuracy: 0.8645 - val_loss: 0.3424
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8603 - loss: 0.3180 - val_accuracy: 0.8620 - val_loss: 0.3429
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8677 - loss: 0.3075 - val_accuracy: 0.8555 - val_loss: 0.3433
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8710 - loss: 0.3042 - val_accuracy: 0.8610 - val_loss: 0.3402
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - loss: 0.2996 - val_accuracy: 0.8655 - val_loss: 0.3409
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8696 - loss: 0.3020 - val_accuracy: 0.8580 - val_loss: 0.3453
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8761 - loss: 0.2992 - val_accuracy: 0.8580 - val_loss: 0.3433
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8775 - loss: 0.2877 - val_accuracy: 0.8590 - val_loss: 0.3410
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [14]:
# Accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100}%")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 85.9%
Confusion Matrix:
[[1522   85]
 [ 197  196]]

In [15]:
model_tanh = Sequential()
model_tanh.add(Dense(64, input_dim=X_train.shape[1], activation='tanh'))
model_tanh.add(Dense(32, activation='tanh'))
model_tanh.add(Dense(1, activation='sigmoid'))
model_tanh.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_tanh.fit(X_train_scaled, y_train, epochs=20, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluating model with 'tanh'
y_pred_tanh = (model_tanh.predict(X_test_scaled) > 0.5).astype(int)
accuracy_tanh = accuracy_score(y_test, y_pred_tanh)
print(f"Accuracy with Tanh activation: {accuracy_tanh * 100:.2f}%")

Epoch 1/20

C:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7443 - loss: 0.5244 - val_accuracy: 0.8235 - val_loss: 0.4044
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8215 - loss: 0.4084 - val_accuracy: 0.8395 - val_loss: 0.3816
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8444 - loss: 0.3726 - val_accuracy: 0.8580 - val_loss: 0.3589
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8512 - loss: 0.3602 - val_accuracy: 0.8570 - val_loss: 0.3503
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8561 - loss: 0.3445 - val_accuracy: 0.8610 - val_loss: 0.3482
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8567 - loss: 0.3464 - val_accuracy: 0.8600 - val_loss: 0.3446
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8576 - loss: 0.3492 - val_accuracy: 0.8545 - val_loss: 0.3454
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3337 - val_accuracy: 0.8575 - val_loss: 0.3448
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8585 - loss: 0.3498 - val_accuracy: 0.8590 - val_loss: 0.3371
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8643 - loss: 0.3354 - val_accuracy: 0.8605 - val_loss: 0.3367
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8522 - loss: 0.3535 - val_accuracy: 0.8575 - val_loss: 0.3417
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8572 - loss: 0.3434 - val_accuracy: 0.8595 - val_loss: 0.3396
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8593 - loss: 0.3341 - val_accuracy: 0.8590 - val_loss: 0.3358
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8654 - loss: 0.3337 - val_accuracy: 0.8565 - val_loss: 0.3389
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8566 - loss: 0.3386 - val_accuracy: 0.8625 - val_loss: 0.3362
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8708 - loss: 0.3225 - val_accuracy: 0.8640 - val_loss: 0.3358
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8628 - loss: 0.3344 - val_accuracy: 0.8605 - val_loss: 0.3375
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3268 - val_accuracy: 0.8550 - val_loss: 0.3381
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8696 - loss: 0.3247 - val_accuracy: 0.8640 - val_loss: 0.3337
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8660 - loss: 0.3287 - val_accuracy: 0.8625 - val_loss: 0.3347
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy with Tanh activation: 86.25%

In [16]:
model_sigmoid = Sequential()


model_sigmoid.add(Dense(64, input_dim=X_train.shape[1], activation='sigmoid'))

model_sigmoid.add(Dense(32, activation='sigmoid'))


model_sigmoid.add(Dense(1, activation='sigmoid'))

model_sigmoid.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


history_sigmoid = model_sigmoid.fit(X_train_scaled, y_train, epochs=20, batch_size=32, validation_data=(X_test_scaled, y_test))

y_pred_sigmoid = (model_sigmoid.predict(X_test_scaled) > 0.5).astype(int)
accuracy_sigmoid = accuracy_score(y_test, y_pred_sigmoid)

print(f"Accuracy with Sigmoid in all layers: {accuracy_sigmoid * 100:.2f}%")
print("Confusion Matrix with Sigmoid in all layers:")
print(confusion_matrix(y_test, y_pred_sigmoid))

Epoch 1/20

C:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7564 - loss: 0.5304 - val_accuracy: 0.8035 - val_loss: 0.4538
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7943 - loss: 0.4592 - val_accuracy: 0.8065 - val_loss: 0.4266
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8071 - loss: 0.4423 - val_accuracy: 0.8130 - val_loss: 0.4261
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8060 - loss: 0.4424 - val_accuracy: 0.8100 - val_loss: 0.4287
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8052 - loss: 0.4445 - val_accuracy: 0.8170 - val_loss: 0.4188
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8091 - loss: 0.4380 - val_accuracy: 0.8215 - val_loss: 0.4148
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8163 - loss: 0.4327 - val_accuracy: 0.8230 - val_loss: 0.4125
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8143 - loss: 0.4324 - val_accuracy: 0.8275 - val_loss: 0.4107
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8254 - loss: 0.4254 - val_accuracy: 0.8325 - val_loss: 0.4059
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8323 - loss: 0.4150 - val_accuracy: 0.8340 - val_loss: 0.4041
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8279 - loss: 0.4176 - val_accuracy: 0.8350 - val_loss: 0.4003
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8354 - loss: 0.4086 - val_accuracy: 0.8405 - val_loss: 0.3949
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8311 - loss: 0.4189 - val_accuracy: 0.8360 - val_loss: 0.3918
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8420 - loss: 0.3886 - val_accuracy: 0.8430 - val_loss: 0.3829
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8394 - loss: 0.3908 - val_accuracy: 0.8460 - val_loss: 0.3783
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8386 - loss: 0.3828 - val_accuracy: 0.8475 - val_loss: 0.3682
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8481 - loss: 0.3727 - val_accuracy: 0.8520 - val_loss: 0.3724
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8531 - loss: 0.3662 - val_accuracy: 0.8540 - val_loss: 0.3550
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8496 - loss: 0.3598 - val_accuracy: 0.8610 - val_loss: 0.3533
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8580 - loss: 0.3566 - val_accuracy: 0.8600 - val_loss: 0.3492
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Accuracy with Sigmoid in all layers: 86.00%
Confusion Matrix with Sigmoid in all layers:
[[1576   31]
 [ 249  144]]